# Generated by Django 5.2.5 on 2025-09-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('file_path', models.CharField(max_length=300)),
                ('is_public', models.BooleanField(default=False)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thumbnail_path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('surname', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('birthdate', models.DateField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('remember_token', models.CharField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('referred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='users_app.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('pending', 'В обработке'), ('declined', 'Оплата не удалась'), ('ready', 'Готов к оплате')], default='ready', max_length=10)),
                ('payment_gateway_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('basic', 'Базовая подписка')], default='basic', max_length=10)),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=10)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users_app.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Подписка активна'), ('outdated', 'Подписка закончилась'), ('not_paid', 'Подписка не оплачена')], default='not_paid', max_length=20)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.user')),
            ],
        ),
    ]
