# Generated by Django 5.2.5 on 2025-09-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_payment_user_alter_usersubscription_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login',
        ),
    ]
