# Generated by Django 5.2.5 on 2025-09-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_remove_userprofile_email_verified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='surname',
        ),
    ]
