# Generated by Django 5.2.5 on 2025-09-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_userprofile_email_verified_at_userprofile_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='remember_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='surname',
        ),
    ]
