# Generated by Django 6.0.5 on 2026-05-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_alter_userprofile_phone_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_msg_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
